name: discuz_flutter
description: Lightweight flutter client for Discuz X

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.7+78

environment:
  sdk: ">=3.0.0 <4.0.0"
#  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.4
  dio: ^5.2.0
  shared_preferences: ^2.0.11
  retrofit: ^4.0.1
  logger: any  #for logging purpose
  settings_ui: ^2.0.2
  form_validator: ^2.1.1
  # persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.2.0
  provider: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.3
  json_serializable: ^6.1.3
  webview_flutter: ^4.0.0
  cookie_jar: ^4.0.7
  dio_cookie_manager: ^3.1.0
  path_provider: ^2.0.8
  progress_state_button: ^1.0.4
  url_launcher: ^6.0.17
  photo_view: ^0.15.0
  permission_handler: ^11.0.0
  # open_file: ^3.2.1
  flutter_slidable:
  webview_cookie_manager: ^2.0.6
  intl: ^0.19.0
  flutter_platform_widgets: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  extended_text_field: ^16.0.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.3.2
  slide_countdown: ^1.6.1

  hive: any
  hive_flutter: any
  device_info_plus: ^10.1.0
  share_plus: ^10.0.0
  firebase_messaging: ^15.0.3
  font_awesome_flutter: ^10.1.0
  firebase_analytics: ^11.2.0
  flutter_local_notifications: ^17.1.2
  # flutter_apns: ^1.6.0
  scroll_to_index: any
  easy_refresh: ^3.0.2+2
  open_filex: ^4.0.1
  flutter_polls: ^0.1.0
  push: ^2.3.0
  google_mobile_ads: ^5.1.0
  image_gallery_saver: ^2.0.3
  dynamic_color: ^1.6.7
  intl_utils: ^2.8.1
  dual_screen: ^1.0.3
  flutter_html_iframe: ^3.0.0-beta.2
  carousel_slider: ^5.0.0
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  upgrader: ^10.3.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  flex_color_picker: ^3.3.1
  google_fonts: ^6.2.1
  chinese_font_library: ^1.1.0
  toastification: ^2.0.0
  haptic_feedback: ^0.5.1+1


  firebase_core: ^3.2.0
  html: ^0.15.4
  ios_utsname_ext: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  retrofit_generator: any
  hive_generator: any





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
