// Generated from the 1,566-name Name That Color list bundled with
// flex_color_picker. Original NTC data by Chirag Mehta (CC BY 2.5).
// Chinese translations are maintained by the Discuz Flutter project.
// https://chir.ag/projects/name-that-color/

/// Simplified-Chinese display names keyed by the original NTC name.
const Map<String, String> ntcColorNamesZh = <String, String>{
  'Black': '黑色',
  'Navy Blue': '海军蓝',
  'Dark Blue': '深蓝色',
  'Blue': '蓝色',
  'Stratos': '斯特拉托斯',
  'Swamp': '沼泽',
  'Resolution Blue': '分辨率蓝色',
  'Deep Fir': '深冷杉',
  'Burnham': '伯纳姆',
  'Klein Blue': '克莱因蓝',
  'Prussian Blue': '普鲁士蓝',
  'Midnight Blue': '午夜蓝',
  'Smalt': '大青蓝',
  'Deep Teal': '深青色',
  'Cyprus': '塞浦路斯',
  'Kaitoke Green': '凯托克格林',
  'Cobalt': '钴',
  'Crusoe': '鲁滨逊绿',
  'Sherpa Blue': '夏尔巴蓝',
  'Endeavour': '奋斗',
  'Camarone': '卡马罗内绿',
  'Science Blue': '科学蓝',
  'Blue Ribbon': '蓝丝带',
  'Tropical Rain Forest': '热带雨林',
  'Allports': '奥尔波特蓝',
  'Deep Cerulean': '深蔚蓝',
  'Lochmara': '洛克马拉蓝',
  'Azure Radiance': '青色光辉',
  'Teal': '青色',
  'Bondi Blue': '邦迪蓝',
  'Pacific Blue': '太平洋蓝',
  'Persian Green': '波斯绿',
  'Jade': '翡翠',
  'Caribbean Green': '加勒比绿',
  'Robin\'s Egg Blue': '知更鸟蛋蓝',
  'Green': '绿色',
  'Spring Green': '斯普林格林',
  'Cyan Aqua': '青色水蓝色',
  'Blue Charcoal': '蓝色木炭',
  'Midnight': '午夜',
  'Holly': '冬青绿',
  'Daintree': '丹翠绿',
  'Cardin Green': '卡丹绿',
  'County Green': '格林郡',
  'Astronaut Blue': '宇航员蓝',
  'Regal Blue': '富豪蓝',
  'Aqua Deep': '水深',
  'Orient': '东方',
  'Blue Stone': '蓝石',
  'Fun Green': '活力绿',
  'Pine Green': '松绿',
  'Blue Lagoon': '蓝色泻湖',
  'Deep Sea': '深海',
  'Green Haze': '绿色雾霾',
  'English Holly': '英国冬青绿',
  'Sherwood Green': '舍伍德格林',
  'Congress Blue': '国会蓝',
  'Evening Sea': '傍晚之海',
  'Bahama Blue': '巴哈马蓝',
  'Observatory': '天文台',
  'Cerulean': '蔚蓝色',
  'Tangaroa': '坦加罗亚',
  'Green Vogue': '绿色VOGUE',
  'Mosque': '清真绿',
  'Midnight Moss': '午夜苔藓',
  'Black Pearl': '黑珍珠',
  'Blue Whale': '蓝鲸',
  'Zuccini': '西葫芦绿',
  'Teal Blue': '蓝绿色',
  'Deep Cove': '深海湾蓝',
  'Gulf Blue': '海湾蓝',
  'Venice Blue': '威尼斯蓝',
  'Watercourse': '水道',
  'Catalina Blue': '卡特琳娜蓝',
  'Tiber': '台伯',
  'Gossamer': '薄纱绿',
  'Niagara': '尼亚加拉',
  'Tarawera': '塔拉韦拉蓝',
  'Jaguar': '捷豹',
  'Black Bean': '黑豆',
  'Deep Sapphire': '深蓝宝石',
  'Elf Green': '精灵绿',
  'Bright Turquoise': '明亮的绿松石色',
  'Downriver': '下游',
  'Palm Green': '棕榈绿',
  'Madison': '麦迪逊',
  'Bottle Green': '瓶绿色',
  'Deep Sea Green': '深海绿',
  'Salem': '塞勒姆',
  'Black Russian': '黑人俄罗斯人',
  'Dark Fern': '暗蕨',
  'Japanese Laurel': '日本月桂',
  'Atoll': '环礁',
  'Cod Gray': '鳕鱼灰',
  'Marshland': '沼泽地',
  'Gordons Green': '戈登斯格林',
  'Black Forest': '黑森林',
  'San Felix': '圣费利克斯',
  'Malachite': '孔雀石',
  'Ebony': '乌木',
  'Woodsmoke': '伍德斯莫克',
  'Racing Green': '赛车绿色',
  'Surfie Green': '冲浪绿',
  'Blue Chill': '冷峻蓝',
  'Black Rock': '黑岩',
  'Bunker': '碉堡',
  'Aztec': '阿兹特克语',
  'Bush': '布什',
  'Cinder': '煤渣',
  'Firefly': '萤火虫',
  'Torea Bay': '托雷亚湾',
  'Vulcan': '瓦肯',
  'Green Waterloo': '滑铁卢绿',
  'Eden': '伊甸园',
  'Arapawa': '阿拉帕瓦',
  'Ultramarine': '群青',
  'Elephant': '大象',
  'Jewel': '珠宝',
  'Diesel': '柴油',
  'Asphalt': '沥青',
  'Blue Zodiac': '蓝色十二生肖',
  'Parsley': '欧芹',
  'Nero': '尼禄',
  'Tory Blue': '托利蓝',
  'Bunting': '彩旗',
  'Denim': '牛仔布',
  'Genoa': '热那亚',
  'Mirage': '海市蜃楼',
  'Hunter Green': '猎人绿',
  'Big Stone': '大石头',
  'Celtic': '凯尔特人',
  'Timber Green': '木材绿',
  'Gable Green': '山墙绿',
  'Pine Tree': '松树',
  'Chathams Blue': '查塔姆蓝',
  'Deep Forest Green': '深森林绿',
  'Blumine': '布卢明蓝',
  'Palm Leaf': '棕榈叶',
  'Nile Blue': '尼罗河蓝',
  'Fun Blue': '活力蓝',
  'Lucky Point': '幸运点',
  'Mountain Meadow': '山间草甸绿',
  'Tolopea': '托洛皮亚紫',
  'Haiti': '海地',
  'Deep Koamaru': '深科阿马鲁蓝',
  'Acadia': '阿卡迪亚',
  'Seaweed': '海藻',
  'Biscay': '比斯开',
  'Matisse': '马蒂斯',
  'Crowshead': '鸦首黑',
  'Rangoon Green': '仰光绿',
  'Persian Blue': '波斯蓝',
  'Everglade': '大沼泽地',
  'Elm': '榆树',
  'Green Pea': '青豌豆',
  'Creole': '克里奥尔语',
  'Karaka': '卡拉卡',
  'El Paso': '埃尔帕索',
  'Cello': '大提琴',
  'Te Papa Green': '蒂帕帕绿',
  'Dodger Blue': '道奇蓝',
  'Eastern Blue': '东方蓝',
  'Night Rider': '夜骑黑',
  'Java': '爪哇青',
  'Jacksons Purple': '杰克逊紫',
  'Cloud Burst': '云爆',
  'Blue Dianne': '黛安娜蓝',
  'Eternity': '永恒',
  'Deep Blue': '深蓝色',
  'Forest Green': '森林绿',
  'Mallard': '野鸭',
  'Violet': '紫罗兰色',
  'Kilimanjaro': '乞力马扎罗山',
  'Log Cabin': '日志小木屋',
  'Black Olive': '黑橄榄',
  'Green House': '温室',
  'Graphite': '石墨',
  'Cannon Black': '黑色大炮',
  'Port Gore': '戈尔港',
  'Shark': '鲨鱼',
  'Green Kelp': '绿海藻',
  'Curious Blue': '好奇蓝',
  'Paua': '鲍鱼壳蓝',
  'Paris M': '巴黎紫',
  'Wood Bark': '木皮',
  'Gondola': '贡多拉',
  'Steel Gray': '钢灰色',
  'Ebony Clay': '乌木粘土',
  'Bay of Many': '群湾蓝',
  'Plantation': '种植园',
  'Eucalyptus': '桉树',
  'Oil': '油',
  'Astronaut': '宇航员',
  'Mariner': '水手',
  'Violent Violet': '暴力紫罗兰',
  'Bastille': '巴士底',
  'Zeus': '宙斯',
  'Charade': '猜谜',
  'Jelly Bean': '果冻豆',
  'Jungle Green': '丛林绿地',
  'Cherry Pie': '樱桃派',
  'Coffee Bean': '咖啡豆',
  'Baltic Sea': '波罗的海',
  'Turtle Green': '海龟绿',
  'Cerulean Blue': '蔚蓝',
  'Sepia Black': '深褐色',
  'Valhalla': '瓦尔哈拉',
  'Heavy Metal': '重金属',
  'Blue Gem': '蓝色宝石',
  'Revolver': '左轮手枪',
  'Bleached Cedar': '漂白雪松',
  'Lochinvar': '洛欣瓦尔绿',
  'Mikado': '米卡多',
  'Outer Space': '外太空',
  'St Tropez': '圣特罗佩',
  'Jacaranda': '蓝花楹紫',
  'Jacko Bean': '杰科豆棕',
  'Rangitoto': '朗伊托托灰',
  'Rhino': '犀牛人',
  'Sea Green': '海绿色',
  'Scooter': '滑板车',
  'Onion': '洋葱',
  'Governor Bay': '总督湾蓝',
  'Sapphire': '蓝宝石',
  'Spectra': '光谱绿',
  'Casal': '卡萨尔',
  'Melanzane': '茄子紫',
  'Cocoa Brown': '可可棕',
  'Woodrush': '伍德拉什',
  'San Juan': '圣胡安',
  'Turquoise': '绿松石',
  'Eclipse': '日食黑',
  'Pickled Bluewood': '腌蓝木',
  'Azure': '蔚蓝',
  'Calypso': '卡吕普索',
  'Paradiso': '天堂绿',
  'Persian Indigo': '波斯靛蓝',
  'Blackcurrant': '黑醋栗',
  'Mine Shaft': '矿井',
  'Stromboli': '斯特龙博利',
  'Bilbao': '毕尔巴鄂',
  'Astral': '星芒',
  'Christalle': '克里斯塔尔',
  'Thunder': '雷',
  'Shamrock': '三叶草',
  'Tamarind': '罗望子',
  'Mardi Gras': '狂欢节',
  'Valentino': '华伦天奴',
  'Jagger': '贾格尔',
  'Tuna': '金枪鱼',
  'Chambray': '尚布雷',
  'Martinique': '马提尼克',
  'Tuatara': '楔齿蜥灰',
  'Waiouru': '怀乌鲁绿',
  'Ming': '明',
  'La Palma': '拉帕尔马',
  'Chocolate': '巧克力',
  'Clinker': '熟料',
  'Brown Tumbleweed': '棕色滚筒草',
  'Birch': '桦木',
  'Oracle': '神谕绿',
  'Blue Diamond': '蓝钻',
  'Grape': '葡萄',
  'Dune': '沙丘',
  'Oxford Blue': '牛津蓝',
  'Clover': '三叶草',
  'Limed Spruce': '石灰云杉灰',
  'Dell': '戴尔',
  'Toledo': '托莱多',
  'Sambuca': '珊布卡',
  'Jacarta': '雅加达紫',
  'William': '威廉绿',
  'Killarney': '基拉尼',
  'Keppel': '吉宝',
  'Temptress': '诱惑紫',
  'Aubergine': '茄子',
  'Jon': '乔恩棕',
  'Treehouse': '树屋',
  'Amazon': '亚马逊绿',
  'Boston Blue': '波士顿蓝',
  'Windsor': '温莎',
  'Rebel': '反抗军',
  'Meteorite': '陨石',
  'Dark Ebony': '深乌木',
  'Camouflage': '伪装',
  'Bright Gray': '亮灰色',
  'Cape Cod': '科德角',
  'Lunar Green': '月岩绿',
  'Bean  ': '豆类',
  'Bistre': '烟褐',
  'Goblin': '哥布林',
  'Kingfisher Daisy': '翠鸟雏菊',
  'Cedar': '雪松',
  'English Walnut': '英式胡桃木',
  'Black Marlin': '黑马林鱼',
  'Ship Gray': '船灰色',
  'Pelorous': '毛茸茸的',
  'Bronze': '青铜',
  'Cola': '可乐',
  'Madras': '马德拉斯',
  'Minsk': '明斯克',
  'Cabbage Pont': '卷心菜绿',
  'Tom Thumb': '拇指汤姆绿',
  'Mineral Green': '矿物绿',
  'Puerto Rico': '波多黎各',
  'Harlequin': '丑角',
  'Brown Pod': '棕色豆荚',
  'Cork': '科克',
  'Masala': '马萨拉',
  'Thatch Green': '茅草绿',
  'Fjord': '峡湾',
  'Viridian': '铬绿',
  'Chateau Green': '城堡绿',
  'Ripe Plum': '成熟李子',
  'Paco': '帕科棕',
  'Deep Oak': '深橡木',
  'Merlin': '梅林',
  'Gun Powder': '火药',
  'East Bay': '东湾',
  'Royal Blue': '皇家蓝',
  'Ocean Green': '海洋绿',
  'Burnt Maroon': '烧焦的栗色',
  'Lisbon Brown': '里斯本布朗',
  'Faded Jade': '褪色的翡翠',
  'Scarlet Gum': '猩红口香糖',
  'Iroko': '非洲柚木棕',
  'Armadillo': '犰狳灰',
  'River Bed': '河床',
  'Green Leaf': '绿叶',
  'Barossa': '巴罗莎',
  'Morocco Brown': '摩洛哥棕色',
  'Mako': '灰鲭鲨灰',
  'Kelp': '海带',
  'San Marino': '圣马力诺',
  'Picton Blue': '皮克顿蓝',
  'Loulou': '露露紫',
  'Crater Brown': '火山口棕色',
  'Gray Asparagus': '灰芦笋',
  'Steel Blue': '钢蓝色',
  'Rustic Red': '乡村红',
  'Bulgarian Rose': '保加利亚玫瑰',
  'Clairvoyant': '千里眼',
  'Cocoa Bean': '可可豆',
  'Woody Brown': '木质棕色',
  'Taupe': '灰褐色',
  'Van Cleef': '梵克雅宝棕',
  'Brown Derby': '布朗德比',
  'Metallic Bronze': '金属青铜',
  'Verdun Green': '凡尔登格林',
  'Blue Bayoux': '蓝色河湾',
  'Bismark': '俾斯麦',
  'Bracken': '布拉肯',
  'Deep Bronze': '深青铜',
  'Mondo': '蒙多',
  'Tundora': '苔原灰',
  'Gravel': '砾石',
  'Trout': '鳟鱼',
  'Pigment Indigo': '色素靛蓝',
  'Nandor': '南多绿',
  'Saddle': '鞍座',
  'Abbey': '修道院',
  'Blackberry': '黑莓',
  'Cab Sav': '赤霞珠红',
  'Indian Tan': '印度棕褐色',
  'Cowboy': '牛仔',
  'Livid Brown': '铅灰棕',
  'Rock': '岩石',
  'Punga': '蓬加棕',
  'Bronzetone': '青铜棕',
  'Woodland': '伍德兰',
  'Mahogany': '桃花心木',
  'Bossanova': '波萨诺瓦紫',
  'Matterhorn': '马特洪峰',
  'Bronze Olive': '青铜橄榄',
  'Mulled Wine': '热红酒紫',
  'Axolotl': '美西螈绿',
  'Wedgewood': '韦奇伍德蓝',
  'Shakespeare': '莎士比亚',
  'Honey Flower': '蜜花',
  'Daisy Bush': '雏菊丛紫',
  'Indigo': '靛蓝',
  'Fern Green': '蕨叶绿',
  'Fruit Salad': '水果沙拉',
  'Apple': '苹果绿',
  'Mortar': '迫击炮',
  'Kashmir Blue': '克什米尔蓝',
  'Cutty Sark': '卡蒂萨克绿',
  'Emerald': '翡翠',
  'Emperor': '皇帝',
  'Chalet Green': '木屋绿',
  'Como': '科莫',
  'Smalt Blue': '大青蓝',
  'Castro': '卡斯特罗',
  'Maroon Oak': '栗色橡木',
  'Gigas': '吉加斯紫',
  'Voodoo': '巫毒',
  'Victoria': '维多利亚州',
  'Hippie Green': '嬉皮绿',
  'Heath': '希思',
  'Judge Gray': '格雷法官',
  'Fuscous Gray': '褐灰色',
  'Vida Loca': '狂野生活绿',
  'Cioccolato': '巧克力棕',
  'Saratoga': '萨拉托加',
  'Finlandia': '芬兰',
  'Havelock Blue': '哈夫洛克蓝',
  'Fountain Blue': '喷泉蓝',
  'Spring Leaves': '春叶',
  'Saddle Brown': '马鞍棕色',
  'Scarpa Flow': '斯卡帕灰',
  'Cactus': '仙人掌',
  'Hippie Blue': '嬉皮士蓝',
  'Wine Berry': '葡萄酒浆果',
  'Brown Bramble': '棕荆棘',
  'Congo Brown': '刚果棕',
  'Millbrook': '米尔布鲁克',
  'Waikawa Gray': '怀卡瓦灰色',
  'Horizon': '地平线',
  'Jambalaya': '什锦饭棕',
  'Bordeaux': '波尔多',
  'Mulberry Wood': '桑木',
  'Carnaby Tan': '卡纳比棕',
  'Comet': '彗星',
  'Redwood': '红杉',
  'Don Juan': '唐璜棕',
  'Chicago': '芝加哥',
  'Verdigris': '铜绿',
  'Dingley': '丁利',
  'Breaker Bay': '碎浪湾蓝',
  'Kabul': '喀布尔',
  'Hemlock': '铁杉',
  'Irish Coffee': '爱尔兰咖啡',
  'Mid Gray': '中灰色',
  'Shuttle Gray': '航天飞机灰',
  'Aqua Forest': '水森林绿',
  'Tradewind': '信风蓝',
  'Horses Neck': '马颈',
  'Smoky': '烟熏',
  'Corduroy': '灯芯绒',
  'Danube': '多瑙河',
  'Espresso': '浓缩咖啡',
  'Eggplant': '茄子',
  'Costa Del Sol': '太阳海岸',
  'Glade Green': '林间空地绿',
  'Buccaneer': '海盗',
  'Quincy': '昆西',
  'Butterfly Bush': '蝴蝶丛',
  'West Coast': '西海岸',
  'Finch': '芬奇',
  'Patina': '铜锈绿',
  'Fern': '蕨类植物',
  'Blue Violet': '蓝紫色',
  'Dolphin': '海豚',
  'Storm Dust': '风暴粉尘',
  'Siam': '暹罗',
  'Nevada': '内华达州',
  'Cornflower Blue': '矢车菊蓝',
  'Viking': '维京蓝',
  'Rosewood': '玫瑰木',
  'Cherrywood': '樱桃木',
  'Purple Heart': '紫心勋章',
  'Fern Frond': '蕨叶绿',
  'Willow Grove': '柳树林绿',
  'Hoki': '霍基蓝',
  'Pompadour': '蓬帕杜尔',
  'Purple': '紫色',
  'Tyrian Purple': '提尔紫',
  'Dark Tan': '深棕褐色',
  'Silver Tree': '银树',
  'Bright Green': '亮绿色',
  'Screamin\' Green': '尖叫绿色',
  'Black Rose': '黑玫瑰',
  'Scampi': '海螯虾紫',
  'Ironside Gray': '铁甲灰',
  'Viridian Green': '铬绿',
  'Christi': '克里斯蒂',
  'Nutmeg Wood Finish': '肉豆蔻木饰面',
  'Zambezi': '赞比西',
  'Salt Box': '盐盒',
  'Tawny Port': '茶色波特红',
  'Finn': '芬恩棕',
  'Scorpion': '蝎子',
  'Lynch': '林奇',
  'Spice': '香料',
  'Himalaya': '喜马拉雅山',
  'Soya Bean': '大豆',
  'Hairy Heath': '毛发健康',
  'Royal Purple': '皇家紫',
  'Shingle Fawn': '木瓦浅棕',
  'Dorado': '多拉多',
  'Bermuda Gray': '百慕大灰',
  'Olive Drab': '橄榄褐',
  'Eminence': '卓越',
  'Turquoise Blue': '绿松石蓝',
  'Lonestar': '孤星红',
  'Pine Cone': '松果',
  'Dove Gray': '鸽子灰',
  'Juniper': '杜松绿',
  'Gothic': '哥特式',
  'Red Oxide': '红色氧化物',
  'Moccaccino': '莫卡奇诺',
  'Pickled Bean': '腌豆',
  'Dallas': '达拉斯',
  'Kokoda': '科科达',
  'Pale Sky': '苍白的天空',
  'Cafe Royale': '皇家咖啡馆',
  'Flint': '弗林特',
  'Highland': '高地',
  'Limeade': '青柠汽水绿',
  'Downy': '唐尼',
  'Persian Plum': '波斯李子',
  'Sepia': '深褐色',
  'Antique Bronze': '古董青铜',
  'Ferra': '费拉',
  'Coffee': '咖啡',
  'Slate Gray': '石板灰',
  'Cedar Wood Finish': '雪松木饰面',
  'Metallic Copper': '金属铜',
  'Affair': '事件',
  'Studio': '单间公寓',
  'Tobacco Brown': '烟草棕',
  'Yellow Metal': '黄色金属',
  'Peat': '泥炭',
  'Olivetone': '橄榄绿',
  'Storm Gray': '风暴灰',
  'Sirocco': '西洛可风灰',
  'Aquamarine Blue': '海蓝色',
  'Venetian Red': '威尼斯红',
  'Old Copper': '老铜',
  'Go Ben': '戈本棕',
  'Raven': '乌鸦',
  'Seance': '降神会紫',
  'Raw Umber': '原始琥珀',
  'Kimberly': '金伯利',
  'Crocodile': '鳄鱼',
  'Crete': '克里特岛',
  'Xanadu': '上都',
  'Spicy Mustard': '辛辣芥末',
  'Limed Ash': '石灰灰',
  'Rolling Stone': '滚石',
  'Blue Smoke': '蓝烟',
  'Laurel': '月桂绿',
  'Mantis': '螳螂女',
  'Russett': '赤褐',
  'Deluge': '洪水',
  'Cosmic': '宇宙系',
  'Blue Marguerite': '蓝色玛格丽特',
  'Lima': '利马',
  'Sky Blue': '天蓝色',
  'Dark Burgundy': '深勃艮第',
  'Crown of Thorns': '荆棘之冠',
  'Walnut': '核桃',
  'Pablo': '巴勃罗',
  'Pacifika': '太平洋绿',
  'Oxley': '奥克斯利',
  'Pastel Green': '柔和绿',
  'Japanese Maple': '日式枫木',
  'Mocha': '摩卡',
  'Peanut': '花生',
  'Camouflage Green': '迷彩绿',
  'Wasabi': '芥末',
  'Ship Cove': '船湾蓝',
  'Sea Nymph': '海仙女',
  'Roman Coffee': '罗马咖啡',
  'Old Lavender': '老薰衣草',
  'Rum': '朗姆酒',
  'Fedora': '软呢帽灰',
  'Sandstone': '砂岩',
  'Spray': '喷雾',
  'Siren': '警笛',
  'Fuchsia Blue': '樱花蓝',
  'Boulder': '博尔德',
  'Wild Blue Yonder': '旷野天蓝',
  'De York': '德约克',
  'Red Beech': '红山毛榉',
  'Cinnamon': '肉桂',
  'Yukon Gold': '育空黄金',
  'Tapa': '塔帕',
  'Waterloo ': '滑铁卢',
  'Flax Smoke': '亚麻烟',
  'Amulet': '护身符',
  'Asparagus': '芦笋',
  'Kenyan Copper': '肯尼亚铜',
  'Pesto': '香蒜酱',
  'Topaz': '黄玉',
  'Concord': '康科德',
  'Jumbo': '珍宝灰',
  'Trendy Green': '时尚绿色',
  'Gumbo': '秋葵汤绿',
  'Acapulco': '阿卡普尔科',
  'Neptune': '海王星',
  'Pueblo': '普韦布洛',
  'Bay Leaf': '月桂叶绿',
  'Malibu': '马里布',
  'Bermuda': '百慕大',
  'Copper Canyon': '铜峡谷',
  'Claret': '波尔多红',
  'Peru Tan': '秘鲁谭',
  'Falcon': '猎鹰',
  'Mobster': '黑手党',
  'Moody Blue': '穆迪蓝',
  'Chartreuse': '沙特鲁斯',
  'Aquamarine': '海蓝宝石',
  'Maroon': '栗色',
  'Rose Bud Cherry': '玫瑰花蕾樱桃',
  'Falu Red': '法鲁红',
  'Red Robin': '红罗宾',
  'Vivid Violet': '鲜艳紫罗兰',
  'Russet': '赤褐',
  'Friar Gray': '修士灰',
  'Olive': '橄榄',
  'Gray': '灰色',
  'Gulf Stream': '墨西哥湾流',
  'Glacier': '冰川',
  'Seagull': '海鸥',
  'Nutmeg': '肉豆蔻',
  'Spicy Pink': '辛辣粉',
  'Empress': '皇后',
  'Spanish Green': '西班牙绿',
  'Sand Dune': '沙丘',
  'Gunsmoke': '枪烟灰',
  'Battleship Gray': '战列舰灰色',
  'Merlot': '梅洛',
  'Shadow': '阴影',
  'Chelsea Cucumber': '切尔西黄瓜',
  'Monte Carlo': '蒙特卡洛',
  'Plum': '梅子',
  'Granny Smith': '史密斯奶奶',
  'Chetwode Blue': '切特沃德蓝',
  'Bandicoot': '袋狸灰',
  'Bali Hai': '巴厘岛海',
  'Half Baked': '半烘焙',
  'Red Devil': '红魔',
  'Lotus': '莲花',
  'Ironstone': '铁石棕',
  'Bull Shot': '公牛烈酒棕',
  'Rusty Nail': '生锈的钉子',
  'Bitter': '苦',
  'Regent Gray': '摄政灰',
  'Disco': '迪斯科',
  'Americano': '美式咖啡棕',
  'Hurricane': '飓风',
  'Oslo Gray': '奥斯陆格雷',
  'Sushi': '寿司',
  'Spicy Mix': '辛辣混合物',
  'Kumera': '甘薯棕',
  'Suva Gray': '苏瓦格雷',
  'Avocado': '牛油果',
  'Camelot': '卡米洛特',
  'Solid Pink': '纯粉色',
  'Cannon Pink': '加农炮粉',
  'Makara': '马卡拉',
  'Burnt Umber': '烧焦的琥珀色',
  'True V': '纯正紫',
  'Clay Creek': '克莱克里克',
  'Monsoon': '季风',
  'Stack': '堆栈',
  'Jordy Blue': '乔迪蓝',
  'Electric Violet': '电动紫罗兰',
  'Monarch': '君主',
  'Corn Harvest': '玉米收获',
  'Olive Haze': '橄榄雾',
  'Schooner': '纵帆船灰',
  'Natural Gray': '天然灰色',
  'Mantle': '地幔',
  'Portage': '波蒂奇蓝',
  'Envy': '嫉妒',
  'Cascade': '级联',
  'Riptide': '激流蓝',
  'Cardinal Pink': '红衣主教粉红色',
  'Mule Fawn': '骡鹿浅棕',
  'Potters Clay': '陶土棕',
  'Trendy Pink': '时尚粉红色',
  'Paprika': '辣椒粉',
  'Sanguine Brown': '血红棕色',
  'Tosca': '托斯卡',
  'Cement': '水泥',
  'Granite Green': '花岗岩绿',
  'Manatee': '海牛',
  'Polo Blue': '马球蓝',
  'Red Berry': '红浆果',
  'Rope': '绳索',
  'Opium': '鸦片',
  'Domino': '多米诺骨牌',
  'Mamba': '曼巴',
  'Nepal': '尼泊尔',
  'Pohutukawa': '新西兰圣诞树红',
  'El Salva': '萨尔瓦',
  'Korma': '咖喱棕',
  'Squirrel': '松鼠',
  'Vista Blue': 'Vista蓝色',
  'Burgundy': '勃艮第',
  'Old Brick': '老砖',
  'Hemp': '大麻',
  'Almond Frost': '杏仁霜',
  'Sycamore': '悬铃木绿',
  'Sangria': '桑格利亚酒',
  'Cumin': '小茴香',
  'Beaver': '海狸',
  'Stonewall': '石墙',
  'Venus': '金星',
  'Medium Purple': '中紫色',
  'Cornflower': '矢车菊',
  'Algae Green': '海藻绿',
  'Copper Rust': '铜锈',
  'Arrowtown': '箭镇灰',
  'Scarlett': '斯嘉丽红',
  'Strikemaster': '突击手紫',
  'Mountain Mist': '山雾',
  'Carmine': '胭脂红',
  'Brown': '棕色',
  'Leather': '皮革',
  'Purple Mountain': '紫山',
  'Lavender Purple': '薰衣草紫',
  'Pewter': '锡',
  'Summer Green': '夏季绿色',
  'Au Chico': '奥奇科棕',
  'Wisteria': '紫藤',
  'Atlantis': '亚特兰蒂斯',
  'Vin Rouge': '葡萄酒红',
  'Lilac Bush': '丁香丛',
  'Bazaar': '集市',
  'Hacienda': '庄园金棕',
  'Pale Oyster': '淡牡蛎',
  'Mint Green': '薄荷绿',
  'Fresh Eggplant': '新鲜茄子',
  'Violet Eggplant': '紫罗兰茄子',
  'Tamarillo': '树番茄红',
  'Totem Pole': '图腾柱',
  'Copper Rose': '铜玫瑰',
  'Amethyst': '紫水晶',
  'Mountbatten Pink': '蒙巴顿粉',
  'Blue Bell': '蓝铃',
  'Prairie Sand': '草原沙红',
  'Toast': '吐司',
  'Gurkha': '廓尔喀语',
  'Olivine': '橄榄石',
  'Shadow Green': '阴影绿',
  'Oregon': '俄勒冈州',
  'Lemon Grass': '柠檬草',
  'Stiletto': '细高跟鞋',
  'Hawaiian Tan': '夏威夷棕褐色',
  'Gull Gray': '海鸥灰',
  'Pistachio': '开心果',
  'Granny Smith Apple': '史密斯奶奶苹果',
  'Anakiwa': '阿纳基瓦蓝',
  'Chelsea Gem': '切尔西宝石',
  'Sepia Skin': '深褐色皮肤',
  'Sage': '鼠尾草',
  'Citron': '柚子',
  'Rock Blue': '岩蓝色',
  'Morning Glory': '牵牛花',
  'Cognac': '干邑白兰地',
  'Reef Gold': '珊瑚礁黄金',
  'Star Dust': '星尘',
  'Santas Gray': '圣塔斯格雷',
  'Sinbad': '辛巴达',
  'Feijoa': '费约果绿',
  'Tabasco': '塔巴斯科州',
  'Buttered Rum': '黄油朗姆酒',
  'Hit Gray': '命中灰色',
  'Citrus': '柑橘',
  'Aqua Island': '水岛蓝',
  'Water Leaf': '水叶',
  'Flirt': '调情',
  'Rouge': '胭脂',
  'Cape Palliser': '帕利瑟角棕',
  'Gray Chateau': '灰色城堡',
  'Edward': '爱德华',
  'Pharlap': '法拉普棕',
  'Amethyst Smoke': '紫水晶烟雾',
  'Blizzard Blue': '暴风雪蓝',
  'Delta': '三角洲灰',
  'Wistful': '渴望',
  'Green Smoke': '绿烟',
  'Jazzberry Jam': '爵士莓果酱红',
  'Zorba': '佐尔巴',
  'Bahia': '巴伊亚',
  'Roof Terracotta': '屋顶兵马俑',
  'Paarl': '帕尔',
  'Barley Corn': '大麦玉米',
  'Donkey Brown': '驴子棕色',
  'Dawn': '黎明',
  'Mexican Red': '墨西哥红',
  'Luxor Gold': '卢克索黄金',
  'Rich Gold': '丰富的黄金',
  'Reno Sand': '里诺沙棕',
  'Coral Tree': '珊瑚树',
  'Dusty Gray': '灰尘灰色',
  'Dull Lavender': '暗淡的薰衣草',
  'Tallow': '牛油',
  'Bud': '芽',
  'Locust': '蝗虫',
  'Norway': '挪威',
  'Chinook': '奇努克',
  'Gray Olive': '灰橄榄',
  'Aluminium': '铝',
  'Cadet Blue': '蓝色学员',
  'Schist': '裂痕',
  'Tower Gray': '塔灰色',
  'Perano': '佩拉诺',
  'Opal': '蛋白石',
  'Night Shadz': '夜影红',
  'Fire': '火灾',
  'Muesli': '什锦麦片棕',
  'Sandal': '凉鞋',
  'Shady Lady': '暗影女士灰',
  'Logan': '洛根',
  'Spun Pearl': '纺珍珠',
  'Regent St Blue': '摄政街蓝',
  'Magic Mint': '魔法薄荷绿',
  'Lipstick': '口红',
  'Royal Heath': '皇家希思',
  'Sandrift': '流沙棕',
  'Cold Purple': '冷紫色',
  'Bronco': '野马',
  'Limed Oak': '石灰橡木棕',
  'East Side': '东区',
  'Lemon Ginger': '柠檬姜',
  'Napa': '纳帕',
  'Hillary': '希拉里',
  'Cloudy': '多云',
  'Silver Chalice': '银色圣杯',
  'Swamp Green': '沼泽绿',
  'Spring Rain': '春雨',
  'Conifer': '针叶树',
  'Celadon': '青玉',
  'Mandalay': '曼德勒',
  'Casper': '卡斯珀',
  'Moss Green': '苔藓绿',
  'Padua': '帕多瓦',
  'Green Yellow': '绿黄色',
  'Hippie Pink': '嬉皮粉',
  'Desert': '沙漠',
  'Bouquet': '花束',
  'Medium Carmine': '中等胭脂红',
  'Apple Blossom': '苹果花',
  'Brown Rust': '棕锈',
  'Driftwood': '漂流木',
  'Alpine': '阿尔卑斯山',
  'Lucky': '幸运',
  'Martini': '马提尼',
  'Bombay': '孟买',
  'Pigeon Post': '信鸽蓝',
  'Cadillac': '凯迪拉克',
  'Matrix': '矩阵',
  'Tapestry': '挂毯',
  'Mai Tai': '迈泰酒橙',
  'Del Rio': '德尔里奥',
  'Powder Blue': '粉蓝色',
  'Inch Worm': '英寸蜗杆',
  'Bright Red': '亮红色',
  'Vesuvius': '维苏威火山',
  'Pumpkin Skin': '南瓜皮',
  'Santa Fe': '圣达菲',
  'Teak': '柚木',
  'Fringy Flower': '边缘花朵',
  'Ice Cold': '冰冷',
  'Shiraz': '设拉子',
  'Biloba Flower': '银杏花紫',
  'Tall Poppy': '高罂粟',
  'Fiery Orange': '火红橙色',
  'Hot Toddy': '热托迪金棕',
  'Taupe Gray': '灰褐色灰色',
  'La Rioja': '拉里奥哈',
  'Well Read': '良好阅读',
  'Blush': '腮红',
  'Jungle Mist': '丛林迷雾',
  'Turkish Rose': '土耳其玫瑰',
  'Lavender': '薰衣草',
  'Mongoose': '猴子',
  'Olive Green': '橄榄绿',
  'Jet Stream': '急流蓝',
  'Cruise': '邮轮',
  'Hibiscus': '芙蓉',
  'Thatch': '茅草',
  'Heathered Gray': '加热灰色',
  'Eagle': '老鹰',
  'Spindle': '主轴',
  'Gum Leaf': '牙龈叶',
  'Rust': '生锈',
  'Muddy Waters': '浑水棕',
  'Sahara': '撒哈拉',
  'Husk': '外壳',
  'Nobel': '诺贝尔奖',
  'Heather': '石南紫',
  'Madang': '马当',
  'Milano Red': '米兰红',
  'Copper': '铜',
  'Gimblet': '吉姆莱特棕',
  'Green Spring': '格林斯普林',
  'Celery': '芹菜',
  'Sail': '帆',
  'Chestnut': '栗子',
  'Crail': '克雷尔红',
  'Marigold': '金盏花',
  'Wild Willow': '野柳',
  'Rainee': '雷尼',
  'Guardsman Red': '红色守卫者',
  'Rock Spray': '岩石喷雾',
  'Bourbon': '波旁威士忌',
  'Pirate Gold': '海盗金币',
  'Nomad': '游牧民族',
  'Submarine': '潜艇',
  'Charlotte': '夏洛特',
  'Medium Red Violet': '中红紫色',
  'Brandy Rose': '白兰地玫瑰',
  'Rio Grande': '里奥格兰德',
  'Surf': '冲浪',
  'Powder Ash': '粉状灰分',
  'Tuscany': '托斯卡纳',
  'Quicksand': '流沙',
  'Silk': '丝绸',
  'Malta': '马耳他',
  'Chatelle': '夏泰尔紫',
  'Lavender Gray': '薰衣草灰',
  'French Gray': '法式灰',
  'Clay Ash': '粘土灰',
  'Loblolly': '火炬松灰',
  'French Pass': '法国通票',
  'London Hue': '伦敦色调',
  'Pink Swan': '粉天鹅',
  'Fuego': '富埃戈',
  'Rose of Sharon': '木槿红',
  'Tide': '潮汐',
  'Blue Haze': '蓝色雾霾',
  'Silver Sand': '银砂',
  'Key Lime Pie': '青柠派绿',
  'Ziggurat': '金字塔蓝',
  'Lime': '青柠',
  'Thunderbird': '雷鸟',
  'Mojo': '魔佐',
  'Old Rose': '老玫瑰',
  'Silver': '银色',
  'Pale Leaf': '苍白的叶子',
  'Pixie Green': '精灵绿',
  'Tia Maria': '蒂亚玛利亚棕',
  'Fuchsia Pink': '紫红色粉红色',
  'Buddha Gold': '佛金',
  'Bison Hide': '野牛皮',
  'Tea': '茶',
  'Gray Suit': '灰色西装',
  'Sprout': '萌芽',
  'Sulu': '苏禄',
  'Indochine': '印度支那',
  'Twine': '麻线',
  'Cotton Seed': '棉籽',
  'Pumice': '浮石',
  'Jagged Ice': '锯齿冰',
  'Maroon Flush': '栗红',
  'Indian Khaki': '印度卡其色',
  'Pale Slate': '苍白石板',
  'Gray Nickel': '灰镍',
  'Periwinkle Gray': 'Periwinkle灰色',
  'Tiara': '头饰',
  'Tropical Blue': '热带蓝',
  'Cardinal': '红衣主教',
  'Fuzzy Wuzzy Brown': '模糊模糊棕色',
  'Orange Roughy': '橙色粗糙面料',
  'Mist Gray': '雾灰',
  'Coriander': '香菜',
  'Mint Tulip': '薄荷郁金香',
  'Mulberry': '桑树',
  'Nugget': '掘金',
  'Tussock': '丛生草棕',
  'Sea Mist': '海雾',
  'Yellow Green': '黄绿色',
  'Brick Red': '砖红色',
  'Contessa': '伯爵夫人',
  'Oriental Pink': '东方粉',
  'Roti': '烤饼棕',
  'Ash': '灰分',
  'Kangaroo': '袋鼠',
  'Las Palmas': '拉斯帕尔马斯',
  'Monza': '蒙扎',
  'Red Violet': '红紫色',
  'Coral Reef': '珊瑚礁',
  'Melrose': '梅尔罗斯',
  'Cloud': '云',
  'Ghost': '幽灵',
  'Pine Glade': '松林绿',
  'Botticelli': '波提切利',
  'Antique Brass': '古董黄铜',
  'Lilac': '丁香',
  'Hokey Pokey': '蜂窝太妃棕',
  'Lily': '百合',
  'Laser': '激光',
  'Edgewater': '埃奇沃特',
  'Piper': '派珀',
  'Pizza': '披萨',
  'Light Wisteria': '浅紫藤',
  'Rodeo Dust': '牛仔竞技尘棕',
  'Sundance': '圣丹斯',
  'Earls Green': '伯爵绿',
  'Silver Rust': '银锈',
  'Conch': '海螺',
  'Reef': '珊瑚礁',
  'Aero Blue': '空气蓝',
  'Flush Mahogany': '亮桃花心木红',
  'Turmeric': '姜黄',
  'Paris White': '巴黎白',
  'Bitter Lemon': '苦柠檬',
  'Skeptic': '怀疑论者',
  'Viola': '中提琴',
  'Foggy Gray': '雾灰色',
  'Green Mist': '绿雾',
  'Nebula': '星云',
  'Persian Red': '波斯红',
  'Burnt Orange': '焦橙',
  'Ochre': '赭石',
  'Puce': '蚤色',
  'Thistle Green': '蓟草绿',
  'Periwinkle': '长春花蓝',
  'Electric Lime': '电石灰',
  'Tenn': '田纳西州',
  'Chestnut Rose': '栗玫瑰',
  'Brandy Punch': '白兰地潘趣酒',
  'Onahau': '奥纳豪蓝',
  'Sorrell Brown': '酸模棕',
  'Cold Turkey': '冷火鸡',
  'Yuma': '尤马',
  'Chino': '奇诺',
  'Eunry': '尤恩里棕',
  'Old Gold': '旧金币',
  'Tasman': '塔斯曼',
  'Surf Crest': '浪峰绿',
  'Humming Bird': '蜂鸟',
  'Scandal': '丑闻',
  'Red Stage': '红色阶段',
  'Hopbush': '啤酒花灌木紫',
  'Meteor': '流星',
  'Perfume': '香水',
  'Prelude': '前奏曲',
  'Tea Green': '茶绿',
  'Geebung': '吉邦金棕',
  'Vanilla': '香草',
  'Soft Amber': '柔和的琥珀色',
  'Celeste': '塞莱斯特',
  'Mischka': '米什卡灰',
  'Pear': '梨',
  'Hot Cinnamon': '热肉桂',
  'Raw Sienna': '生赭',
  'Careys Pink': '凯里粉',
  'Tan': '棕褐色',
  'Deco': '装饰绿',
  'Blue Romance': '蓝色浪漫',
  'Gossip': '八卦',
  'Sisal': '剑麻棕',
  'Swirl': '漩涡',
  'Charm': '魅力',
  'Clam Shell': '蛤壳',
  'Straw': '吸管',
  'Akaroa': '阿卡罗阿',
  'Bird Flower': '鸟花',
  'Iron': '熨斗',
  'Geyser': '间歇泉',
  'Hawkes Blue': '霍克斯蓝',
  'Grenadier': '掷弹兵',
  'Can Can': '罐罐',
  'Whiskey': '威士忌',
  'Winter Hazel': '冬日淡褐色',
  'Granny Apple': '苹果奶奶',
  'My Pink': '我的粉红色',
  'Tacha': '塔查金',
  'Moon Raker': '揽月蓝',
  'Quill Gray': '羽毛灰色',
  'Snowy Mint': '白雪皑皑的薄荷',
  'New York Pink': '纽约粉色',
  'Pavlova': '巴甫洛娃',
  'Fog': '雾',
  'Valencia': '瓦伦西亚',
  'Japonica': '日本木瓜红',
  'Thistle': '蓟',
  'Maverick': '独行者紫',
  'Foam': '泡沫',
  'Cabaret': '歌舞表演',
  'Burning Sand': '燃烧的沙子',
  'Cameo': '浮雕粉',
  'Timberwolf': '森林狼',
  'Tana': '塔纳',
  'Link Water': '链接水',
  'Mabel': '梅布尔',
  'Cerise': '樱桃红',
  'Flame Pea': '火焰豆',
  'Bamboo': '竹子',
  'Red Damask': '红锦缎',
  'Orchid': '兰花',
  'Copperfield': '科波菲尔',
  'Golden Grass': '金草',
  'Zanah': '扎纳绿',
  'Iceberg': '冰山',
  'Oyster Bay': '牡蛎湾',
  'Cranberry': '蔓越莓',
  'Petite Orchid': '娇小的兰花',
  'Di Serria': '迪塞里亚橙',
  'Alto': '奥尔托灰',
  'Frosted Mint': '磨砂薄荷',
  'Crimson': '深红色',
  'Punch': '潘趣酒红',
  'Galliano': '加利亚诺',
  'Blossom': '花朵粉',
  'Wattle': '瓦特尔',
  'Westar': '韦斯塔灰',
  'Moon Mist': '月雾',
  'Caper': '刺山柑绿',
  'Swans Down': '天鹅绒白',
  'Swiss Coffee': '瑞士咖啡',
  'White Ice': '白冰',
  'Cerise Red': '樱桃红',
  'Roman': '罗马红',
  'Tumbleweed': '风滚草棕',
  'Gold Tips': '金牌建议',
  'Brandy': '白兰地',
  'Wafer': '晶圆',
  'Sapling': '树苗',
  'Barberry': '小檗黄',
  'Beryl Green': '绿柱石绿',
  'Pattens Blue': '帕滕斯蓝',
  'Heliotrope': '天芥菜紫',
  'Apache': '阿帕奇',
  'Chenin': '白诗南金',
  'Lola': '萝拉',
  'Willow Brook': '柳溪绿',
  'Chartreuse Yellow': '查特酒黄',
  'Mauve': '淡紫',
  'Anzac': '澳新军团棕',
  'Harvest Gold': '收获金币',
  'Calico': '印花布棕',
  'Baby Blue': '浅蓝色',
  'Sunglo': '阳光红',
  'Equator': '赤道',
  'Pink Flare': '粉色耀斑',
  'Periglacial Blue': '冰缘蓝',
  'Kidnapper': '绑架者',
  'Tara': '塔拉',
  'Mandy': '曼迪红',
  'Terracotta': '兵马俑',
  'Golden Bell': '金钟',
  'Shocking': '令人震惊',
  'Dixie': '迪克西',
  'Light Orchid': '浅兰花',
  'Snuff': '鼻烟',
  'Mystic': '神秘系',
  'Apple Green': '苹果绿',
  'Razzmatazz': '炫彩莓红',
  'Alizarin Crimson': '茜素深红',
  'Cinnabar': '朱砂',
  'Cavern Pink': '洞穴粉',
  'Peppermint': '薄荷',
  'Mindaro': '明达罗绿',
  'Deep Blush': '深腮红',
  'Gamboge': '藤黄',
  'Melanie': '梅拉妮粉',
  'Twilight': '暮光之城',
  'Bone': '骨骼',
  'Sunflower': '向日葵',
  'Grain Brown': '谷物棕色',
  'Zombie': '僵尸',
  'Frostee': '弗罗斯蒂',
  'Snow Flurry': '暴风雪',
  'Amaranth': '苋菜',
  'Zest': '柑橘皮橙',
  'Dust Storm': '沙尘暴',
  'Stark White': '史塔克·怀特',
  'Hampton': '汉普顿',
  'Bon Jour': '日安灰',
  'Mercury': '水星',
  'Polar': '极地',
  'Trinidad': '特立尼达',
  'Gold Sand': '金砂',
  'Cashmere': '羊绒',
  'Double Spanish White': '双西班牙白',
  'Satin Linen': '缎面亚麻',
  'Harp': '竖琴',
  'Off Green': '灰白绿',
  'Hint of Green': '绿色提示',
  'Tranquil': '宁静',
  'Mango Tango': '芒果探戈',
  'Christine': '克里斯汀橙',
  'Tony\'s Pink': '托尼粉',
  'Kobi': '科比粉',
  'Rose Fog': '玫瑰雾',
  'Corn': '玉米',
  'Putty': '腻子',
  'Gray Nurse': '灰色护士',
  'Lily White': '莉莉·怀特',
  'Bubbles': '气泡',
  'Fire Bush': '消防灌木丛',
  'Shilo': '希洛粉',
  'Pearl Bush': '珍珠布什',
  'Green White': '绿色白色',
  'Chrome White': '铬白',
  'Gin': '杜松子酒',
  'Aqua Squeeze': '水雾绿',
  'Clementine': '克莱门汀',
  'Burnt Sienna': '熟赭',
  'Tahiti Gold': '大溪地黄金',
  'Oyster Pink': '牡蛎粉',
  'Confetti': '纸屑',
  'Ebb': '退潮',
  'Ottoman': '奥斯曼帝国',
  'Clear Day': '晴天',
  'Carissma': '卡里斯玛粉',
  'Porsche': '保时捷',
  'Tulip Tree': '郁金香树',
  'Rob Roy': '罗布罗伊金',
  'Raffia': '拉菲亚',
  'White Rock': '怀特罗克',
  'Panache': '潇洒绿',
  'Solitude': '孤独',
  'Aqua Spring': '水泉绿',
  'Dew': '露水',
  'Apricot': '杏',
  'Zinnwaldite': '铁锂云母棕',
  'Fuel Yellow': '燃油黄',
  'Ronchi': '龙基金',
  'French Lilac': '法式丁香',
  'Just Right': '恰到好处',
  'Wild Rice': '野生大米',
  'Fall Green': '秋叶绿',
  'Aths Special': 'Aths特惠',
  'Starship': '星际飞船',
  'Red Ribbon': '红丝带',
  'Tango': '探戈',
  'Carrot Orange': '胡萝卜橙',
  'Sea Pink': '海粉色',
  'Tacao': '塔考橙',
  'Desert Sand': '沙漠沙',
  'Pancho': '潘乔',
  'Chamois': '麂皮棕',
  'Primrose': '月见草',
  'Frost': '霜冻',
  'Aqua Haze': '水雾',
  'Zumthor': '卒姆托蓝',
  'Narvik': '纳尔维克',
  'Honeysuckle': '金银花',
  'Lavender Magenta': '薰衣草洋红',
  'Beauty Bush': '美容灌木丛',
  'Chalky': '粉笔黄',
  'Almond': '杏仁',
  'Flax': '亚麻',
  'Bizarre': '奇怪',
  'Double Colonial White': '双殖民地白',
  'Cararra': '卡拉拉',
  'Manz': '曼兹',
  'Tahuna Sands': '塔胡纳沙黄',
  'Athens Gray': '雅典灰',
  'Tusk': '牙齿',
  'Loafer': '乐福鞋',
  'Catskill White': '卡茨基尔白',
  'Twilight Blue': '暮光之蓝',
  'Jonquil': '长寿花黄',
  'Rice Flower': '米花',
  'Jaffa': '雅法',
  'Gallery': '图库',
  'Porcelain': '瓷器',
  'Mauvelous': '奇妙淡紫',
  'Golden Dream': '黄金梦',
  'Golden Sand': '金沙',
  'Buff': '增益',
  'Prim': '淡紫报春',
  'Khaki': '卡其色',
  'Selago': '塞拉戈',
  'Titan White': '泰坦白',
  'Alice Blue': '爱丽丝蓝',
  'Feta': '菲塔',
  'Gold Drop': '金币掉落',
  'Wewak': '韦瓦克',
  'Sahara Sand': '撒哈拉沙',
  'Parchment': '羊皮纸',
  'Blue Chalk': '蓝色粉笔',
  'Mint Julep': '薄荷朱丽普',
  'Seashell': '贝壳',
  'Saltpan': '盐田白',
  'Tidal': '潮汐',
  'Chiffon': '雪纺',
  'Flamingo': '火烈鸟',
  'Tangerine': '橘子',
  'Mandy\'s Pink': '曼迪粉',
  'Concrete': '混凝土',
  'Black Squeeze': '黑色挤压',
  'Pomegranate': '石榴',
  'Buttercup': '毛茛黄',
  'New Orleans': '新奥尔良',
  'Vanilla Ice': '香草冰',
  'Sidecar': '边车鸡尾酒黄',
  'Dawn Pink': '黎明粉',
  'Wheatfield': '麦田',
  'Canary': '金丝雀',
  'Orinoco': '奥里诺科',
  'Carla': '卡拉',
  'Hollywood Cerise': '好莱坞樱桃红',
  'Sandy brown': '沙棕色',
  'Saffron': '藏红花',
  'Ripe Lemon': '熟柠檬',
  'Janna': '珍娜米白',
  'Pampas': '潘帕斯州',
  'Wild Sand': '野生沙子',
  'Zircon': '锆石',
  'Froly': '弗罗利粉',
  'Cream Can': '奶油罐',
  'Manhattan': '曼哈顿',
  'Maize': '玉米',
  'Wheat': '小麦',
  'Sandwisp': '沙雾黄',
  'Pot Pourri': '百花香粉',
  'Albescent White': '微白',
  'Soft Peach': '软桃',
  'Ecru White': '本白',
  'Beige': '米色',
  'Golden Fizz': '金色气泡黄',
  'Australian Mint': '澳大利亚铸币厂',
  'French Rose': '法国玫瑰',
  'Brilliant Rose': '璀璨玫瑰',
  'Illusion': '错觉',
  'Merino': '美利奴',
  'Black Haze': '黑雾',
  'Spring Sun': '春日太阳光',
  'Violet Red': '紫罗兰红',
  'Chilean Fire': '智利大火',
  'Persian Pink': '波斯粉',
  'Rajah': '王侯金',
  'Azalea': '杜鹃花',
  'We Peep': '窥视粉',
  'Quarter Spanish White': '四分之一西班牙白',
  'Whisper': '低语',
  'Snow Drift': '积雪漂移',
  'Casablanca': '卡萨布兰卡',
  'Chantilly': '尚蒂伊',
  'Cherub': '基路伯',
  'Marzipan': '杏仁糖黄',
  'Energy Yellow': '能量黄',
  'Givry': '日夫里米黄',
  'White Linen': '白色亚麻',
  'Magnolia': '木兰白',
  'Spring Wood': '斯普林伍德',
  'Coconut Cream': '椰子奶油',
  'White Lilac': '白丁香',
  'Desert Storm': '沙漠风暴',
  'Texas': '德克萨斯州',
  'Corn Field': '玉米田',
  'Mimosa': '含羞草',
  'Carnation': '康乃馨',
  'Saffron Mango': '藏红花芒果',
  'Carousel Pink': '旋转木马粉色',
  'Dairy Cream': '乳霜',
  'Portica': '波蒂卡',
  'Amour': '爱恋粉',
  'Rum Swizzle': '朗姆调酒米白',
  'Dolly': '多莉',
  'Sugar Cane': '甘蔗',
  'Ecstasy': '摇头丸',
  'Tan Hide': '棕褐色隐藏',
  'Corvette': '科尔维特金',
  'Peach Yellow': '桃黄',
  'Turbo': '涡轮增压',
  'Astra': '阿斯特拉',
  'Champagne': '香槟',
  'Linen': '布草',
  'Fantasy': '幻想',
  'Citrine White': '黄水晶白',
  'Alabaster': '雪花石膏',
  'Hint of Yellow': '黄色提示',
  'Milan': '米兰',
  'Brink Pink': '粉红色粉红色',
  'Geraldine': '杰拉尔丁',
  'Lavender Rose': '薰衣草玫瑰',
  'Sea Buckthorn': '沙棘',
  'Sun': '周日',
  'Lavender Pink': '薰衣草粉',
  'Rose Bud': '玫瑰花蕾',
  'Cupid': '丘比特',
  'Classic Rose': '经典玫瑰',
  'Apricot Peach': '杏桃',
  'Banana Mania': '香蕉狂热',
  'Marigold Yellow': '万寿菊黄',
  'Festival': '节日',
  'Sweet Corn': '甜玉米',
  'Candy Corn': '玉米糖',
  'Hint of Red': '暗淡的红色',
  'Shalimar': '夏利马尔黄',
  'Shocking Pink': '令人震惊的粉红色',
  'Tickle Me Pink': '挠痒粉',
  'Tree Poppy': '树罂粟',
  'Lightning Yellow': '闪电黄',
  'Goldenrod': '一枝黄花金',
  'Candlelight': '烛光',
  'Cherokee': '切罗基语',
  'Double Pearl Lusta': '双倍珍珠光泽白',
  'Pearl Lusta': '珍珠光泽白',
  'Vista White': '远景白',
  'Bianca': '比安卡',
  'Moon Glow': '月光',
  'China Ivory': '中国象牙',
  'Ceramic': '陶瓷',
  'Torch Red': '火炬红',
  'Wild Watermelon': '野生西瓜',
  'Crusta': '克鲁斯塔',
  'Sorbus': '索布斯',
  'Sweet Pink': '甜粉色',
  'Light Apricot': '浅杏',
  'Pig Pink': '猪粉',
  'Cinderella': '灰姑娘',
  'Golden Glow': '金色光芒',
  'Lemon': '柠檬',
  'Old Lace': '老蕾丝',
  'Half Colonial White': '半殖民地白',
  'Drover': '牧人黄',
  'Pale Prim': '淡报春黄',
  'Cumulus': '积云',
  'Persian Rose': '波斯玫瑰',
  'Sunset Orange': '日落橙',
  'Bittersweet': '苦甜',
  'California': '加利福尼亚州',
  'Yellow Sea': '黄海',
  'Melon': '瓜',
  'Bright Sun': '灿烂阳光',
  'Dandelion': '蒲公英',
  'Salomie': '萨洛米黄',
  'Cape Honey': '海角蜂蜜黄',
  'Remy': '雷米',
  'Oasis': '绿洲',
  'Bridesmaid': '伴娘',
  'Beeswax': '蜂蜡',
  'Bleach White': '漂白剂白色',
  'Pipi': '皮皮米黄',
  'Half Spanish White': '半西班牙白',
  'Wisp Pink': '精灵粉',
  'Provincial Pink': '省粉色',
  'Half Dutch White': '半荷兰白',
  'Solitaire': '纸牌',
  'White Pointer': '白色指针',
  'Off Yellow': '灰白黄',
  'Orange White': '橙白',
  'Red': '红色',
  'Rose': '玫瑰',
  'Purple Pizzazz': '炫目紫',
  'Magenta / Fuchsia': '洋红色/樱红色',
  'Scarlet': '猩红',
  'Wild Strawberry': '野草莓',
  'Razzle Dazzle Rose': '炫目玫红',
  'Radical Red': '自由基红色',
  'Red Orange': '红橙',
  'Coral Red': '珊瑚红',
  'Vermilion': '朱红色',
  'International Orange': '国际橙',
  'Outrageous Orange': '离谱的橙色',
  'Blaze Orange': '火焰橙',
  'Pink Flamingo': '粉红色火烈鸟',
  'Orange': '橙色',
  'Hot Pink': '辣粉红色',
  'Persimmon': '柿子',
  'Blush Pink': '腮红粉红色',
  'Burning Orange': '燃烧的橙色',
  'Pumpkin': '南瓜',
  'Flamenco': '弗拉门戈',
  'Flush Orange': '橙色齐平',
  'Coral': '珊瑚',
  'Salmon': '三文鱼',
  'Pizazz': '活力橙',
  'West Side': '西区',
  'Pink Salmon': '粉红三文鱼',
  'Neon Carrot': '霓虹胡萝卜',
  'Atomic Tangerine': '原子橘',
  'Vivid Tangerine': '鲜艳的橘子',
  'Sunshade': '遮阳帘',
  'Orange Peel': '橙皮',
  'Mona Lisa': '蒙娜丽莎',
  'Web Orange': '网页橙色',
  'Carnation Pink': '康乃馨粉',
  'Hit Pink': '命中粉红色',
  'Yellow Orange': '黄橙',
  'Cornflower Lilac': '矢车菊丁香紫',
  'Sundown': '日落粉',
  'My Sin': '罪恶金',
  'Texas Rose': '得克萨斯玫瑰橙',
  'Cotton Candy': '棉花糖粉',
  'Macaroni and Cheese': '芝士通心粉橙',
  'Selective Yellow': '选择性黄',
  'Koromiko': '科罗米科橙',
  'Amber': '琥珀色',
  'Wax Flower': '蜡花粉',
  'Pink': '粉色',
  'Your Pink': '你的粉',
  'Supernova': '超新星黄',
  'Flesh': '肤色',
  'Sunglow': '阳光黄',
  'Golden Tainoi': '金色泰诺伊',
  'Peach Orange': '桃橙',
  'Chardonnay': '霞多丽黄',
  'Pastel Pink': '柔和粉',
  'Romantic': '浪漫粉',
  'Grandis': '格兰迪斯橙',
  'Gold': '金色',
  'School bus Yellow': '校车黄',
  'Cosmos': '宇宙粉',
  'Mustard': '芥末黄',
  'Peach Schnapps': '桃味杜松子酒粉',
  'Caramel': '焦糖色',
  'Tuft Bush': '绒簇粉',
  'Watusi': '瓦图西粉',
  'Pink Lace': '粉色蕾丝',
  'Navajo White': '纳瓦霍白',
  'Frangipani': '鸡蛋花黄',
  'Pippin': '皮平粉',
  'Pale Rose': '淡玫瑰粉',
  'Negroni': '内格罗尼橙',
  'Cream Brulee': '焦糖布丁黄',
  'Peach': '桃色',
  'Tequila': '龙舌兰黄',
  'Kournikova': '库尔尼科娃黄',
  'Sandy Beach': '沙滩黄',
  'Karry': '卡里米黄',
  'Broom': '金雀花黄',
  'Colonial White': '殖民地白',
  'Derby': '德比米黄',
  'Vis Vis': '维斯维斯黄',
  'Egg White': '蛋白色',
  'Papaya Whip': '木瓜奶油色',
  'Fair Pink': '柔美粉',
  'Peach Cream': '桃子奶油色',
  'Lavender blush': '薰衣草红晕',
  'Gorse': '荆豆黄',
  'Buttermilk': '酪乳黄',
  'Pink Lady': '粉红佳人',
  'Forget Me Not': '勿忘我粉',
  'Tutu': '芭蕾裙粉',
  'Picasso': '毕加索黄',
  'Chardon': '沙尔东粉',
  'Paris Daisy': '巴黎雏菊黄',
  'Barley White': '大麦白',
  'Egg Sour': '蛋酸酒黄',
  'Sazerac': '萨泽拉克米黄',
  'Serenade': '小夜曲粉',
  'Chablis': '夏布利粉',
  'Seashell Peach': '贝壳桃色',
  'Sauvignon': '长相思粉',
  'Milk Punch': '牛奶潘趣黄',
  'Varden': '瓦登米黄',
  'Rose White': '玫瑰白',
  'Baja White': '下加利福尼亚白',
  'Gin Fizz': '金菲士米黄',
  'Early Dawn': '破晓黄',
  'Lemon Chiffon': '柠檬雪纺黄',
  'Bridal Heath': '新娘石南白',
  'Scotch Mist': '苏格兰薄雾黄',
  'Soapstone': '皂石白',
  'Witch Haze': '女巫薄雾黄',
  'Buttery White': '黄油白',
  'Island Spice': '海岛香料白',
  'Cream': '奶油色',
  'Chilean Heath': '智利石南白',
  'Travertine': '洞石白',
  'Orchid White': '兰花白',
  'Quarter Pearl Lusta': '四分之一珍珠光泽白',
  'Half and Half': '半乳白',
  'Apricot White': '杏白',
  'Rice Cake': '米糕白',
  'Black White': '黑白灰',
  'Romance': '浪漫白',
  'Yellow': '黄色',
  'Laser Lemon': '激光柠檬黄',
  'Pale Canary': '淡金丝雀黄',
  'Portafino': '波托菲诺黄',
  'Ivory': '象牙白',
  'White': '白色',
};
