// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8d6brTx2iU-00YfJrzV24ONoCJFCgMgU',
    appId: '1:7909980581:web:feb007a7996aa655c5904c',
    messagingSenderId: '7909980581',
    projectId: 'discuz-hub',
    authDomain: 'discuz-hub.firebaseapp.com',
    storageBucket: 'discuz-hub.appspot.com',
    measurementId: 'G-NLTRJH9BZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbdA8cssVh67IxupJk76ueGaIxpTPtHo',
    appId: '1:7909980581:android:a25e7fa38e0af05ec5904c',
    messagingSenderId: '7909980581',
    projectId: 'discuz-hub',
    storageBucket: 'discuz-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnefPA_sGbr6jqwCPbEWtzeylHtGILsU',
    appId: '1:7909980581:ios:3533283933f3b4f9c5904c',
    messagingSenderId: '7909980581',
    projectId: 'discuz-hub',
    storageBucket: 'discuz-hub.appspot.com',
    iosClientId: '7909980581-qibjv0bedppchiou9pbloarivckc9d4v.apps.googleusercontent.com',
    iosBundleId: 'com.kidozh.discuz-flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnefPA_sGbr6jqwCPbEWtzeylHtGILsU',
    appId: '1:7909980581:ios:92717f8cc2d37f29c5904c',
    messagingSenderId: '7909980581',
    projectId: 'discuz-hub',
    storageBucket: 'discuz-hub.appspot.com',
    iosClientId: '7909980581-c022u0dgqmks81dbngfkrkg7ir0ic4kd.apps.googleusercontent.com',
    iosBundleId: 'com.kidozh.discuzFlutter',
  );
}
