// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:discuz_flutter/entity/BlockUser.dart';
import 'package:discuz_flutter/entity/Discuz.dart';
import 'package:discuz_flutter/entity/DiscuzAuthentication.dart';
import 'package:discuz_flutter/entity/Draft.dart';
import 'package:discuz_flutter/entity/FavoriteForumInDatabase.dart';
import 'package:discuz_flutter/entity/FavoriteThreadInDatabase.dart';
import 'package:discuz_flutter/entity/ImageAttachment.dart';
import 'package:discuz_flutter/entity/Smiley.dart';
import 'package:discuz_flutter/entity/TrustHost.dart';
import 'package:discuz_flutter/entity/User.dart';
import 'package:discuz_flutter/entity/ViewHistory.dart';
import 'package:discuz_flutter/entity/ViewThreadCache.dart';
import 'package:discuz_flutter/entity/ViewThreadScrollDistance.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BlockUserAdapter());
    registerAdapter(DiscuzAdapter());
    registerAdapter(DiscuzAuthenticationAdapter());
    registerAdapter(DraftAdapter());
    registerAdapter(FavoriteForumInDatabaseAdapter());
    registerAdapter(FavoriteThreadInDatabaseAdapter());
    registerAdapter(ImageAttachmentAdapter());
    registerAdapter(SmileyAdapter());
    registerAdapter(TrustHostAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(ViewHistoryAdapter());
    registerAdapter(ViewThreadCacheAdapter());
    registerAdapter(ViewThreadScrollDistanceAdapter());
  }
}
